#!/bin/sh

PROGNAME="$0"

usage() {
	cat <<EOF
NAME
    `basename $PROGNAME` - Anything to cryptogram

SYNOPSIS
    `basename $PROGNAME` [options] [thing] ...

DESCRIPTION
    Decimal to cryptogram.  Actually "decimal" should be "anything" to
    cryptogram.

    Normally, there is a filter which deletes "(),.".

OPTIONS
    -f		No filter at all
    -s thing	Spaces are "thing"
    -D lvl	Debug level

EXAMPLES
    Processing from stdin:

	$ decimal2cryptogram
	81 56 57 58 54 72 55 72 58 66 56 81 41 53 41
	42 57 41 41 63 41 55 42 54 58 41 41 81 46 56
	55 81 58 81 55 81 41 41 55 42 54 58 48 41 57 56
	ABCDEFGFDHBAIJIKCIILIGKEDIIAMBGADAGAIIGKEDNICO

    Then, go online to http://www.quipqiup.com/ :

        in:	ABCDEFGFDHBAIJIKCIILIGKEDIIAMBGADAGAIIGKEDNICO
	out:	NORTH FIFTY ONE DEGREE KEIGHTEEN POINT NINE EIGHT SERV

    Hexadecimal:

	$ decimal2cryptogram 
	2c 7f 24 24 5a 20  7c 26 6a 07 63 5a 6a 20 
	4e 20 63 5a 6a 67 1c 6a  4e 7c 6a 1b 6a 01 01 6a
	41 01 64 49 54 34 6a 5c  6a 28 14 01 6a 61 0f 64
	14 28 34
	ABCCDEFGHIJDHEKEJDHLMHKFHNHOOHPOQRSTHUHVWOHXYQWVT

    Spaces:

	$ decimal2cryptogram -s 00
	18 24 34 47 00 34 47 00 12 00 35 34
	ABCD CD E FC

    Process https://coord.info/GC7PRQ3 :

	$ decimal2cryptogram -s -
	8 9 12 8 19 9 - 7 26 19 19 - 16 9 - 16 26 25 - 26 13 25 -
	10 16 - 13 12 1 - 23 2 6 9 - 15 5 14 - 10 - 15 9 26 6 - 26 -
	13 10 7 9 - 20 6 9 9 13 - 5 26 1 - 26 13 25 - 10 - 19 12 17 9 -
	1 9 26 - 1 5 9 - 12 13 19 14 - 1 5 10 13 20 - 10 - 19 12 17 9 -
	16 12 6 9 - 1 5 26 13 - 26 - 1 9 26 - 8 26 6 1 14 -
	ABCADB EFDD GB GFH FIH JG ICK LMNB OPQ J OBFN F IJEB RNBBI PFK
	FIH J DCSB KBF KPB CIDQ KPJIR J DCSB GCNB KPFI F KBF AFNKQ 
	https://quipqiup.com/
	PEOPLE CALL ME MAD AND I'M NOT SURE WHY I WEAR A NICE GREEN HAT
	AND I LOVE TEA THE ONLY THING I LOVE MORE THAN A TEA PARTY

    Process https://coord.info/GC7TF69 :

	$ sed 's/./& /g' xxx | decimal2cryptogram -f
	ABCDEFGHIAGAIDJBKGLFGHIKIHIAFGHIIMKDNICBNICBIGOEDNICBNICBAGAIKIHIAKGL
	https://quipqiup.com/
	Clues:	a=n b=o c=r d=t e=h
	NORTH FIVE NINE TWO SIX FIVE SEVEN FIVE
	EAST PERO PERO EIGHT PERO PERO NINE SEVEN SIX

SEE ALSO
    http://www.quipqiup.com/
EOF

	exit 1
}

#
#       Report an error and exit
#
error() {
	echo "`basename $PROGNAME`: $1" >&2
	exit 1
}

debug() {
	if [ $DEBUG -ge $1 ]; then
	    echo "`basename $PROGNAME`: $2" >&2
	fi
}

#
#       Process the options
#
DEBUG=0
SPACE=
FILTER="tr -d '(),.'"
while getopts "fs:D:h?" opt
do
	case $opt in
	f)	FILTER="cat";;
	s)	SPACE="$OPTARG";;
	D)	DEBUG="$OPTARG";;
	h|\?)	usage;;
	esac
done
shift `expr $OPTIND - 1`

#
#	Main Program
#
doit() {
    $FILTER | awk -v "SPACE=$SPACE" '
    function chr(c)
    {
	# force c to be numeric by adding 0
	return sprintf("%c", c + 0)
    }
    {
	for (i=1; i <= NF; ++i)
	{
	    if (SPACE == $i)
	    {
		printf " "
		continue
	    }
	    if (a[$i] == "")
	    {
		a[$i] = chr(64 + ++x)
	    }
	    printf "%s", a[$i]
	}
    }
    END {
	printf "\n"
    }
    '
}

if [ $# = 0 ]; then
    doit
else
    echo "$*" | doit
fi
