#!/bin/sh

PROGNAME="$0"

usage() {
	cat <<EOF
NAME
    `basename $PROGNAME` - procmailrc script for geocaching

SYNOPSIS
    `basename $PROGNAME` [options]

DESCRIPTION
    This is a procmailrc script for geocaching.  It will turn
    the "http://www.geocaching.com/seek/cache_details.aspx?..."
    into "http://www.geocaching.com/seek/cdpf.aspx?" so that
    you can get the print-friendly pages.

EXAMPLE
    In \$HOME/.procmailrc:

	#
	#       GEO: Print friendly, decrypt
	#
	:0f
	* ^Subject:.*GEO] Notify: Surfer Joe
	| geo-procmail

OPTIONS
    -D lvl	Debug level
EOF

	exit 1
}

#
#       Report an error and exit
#
error() {
	echo "`basename $PROGNAME`: $1" >&2
	exit 1
}

debug() {
	if [ $DEBUG -ge $1 ]; then
	    echo "`basename $PROGNAME`: $2" >&2
	fi
}

#
#       Process the options
#
DEBUG=0
#unset OPTIND
while getopts "D:h?" opt
do
	case $opt in
	D)	DEBUG="$OPTARG";;
	h|\?)	usage;;
	esac
done
shift `expr $OPTIND - 1`

#
#	Main Program
#
sed \
    -e 's@.*/cache_details.aspx?.*@&\
&@' \
    -e 's@/cache_details.aspx?@/cdpf.aspx?decrypt=1\&@' \
    $*

# sed 's@http://www.geocaching.com/seek/cache_details.aspx?@http://www.geocaching.com/seek/cdpf.aspx?decrypt=1\&@'
# sed <zzz -e 's/.*ello.*/&\n&/' -e 's/button .b/but bb/'


