#!/bin/sh

PROGNAME="$0"

usage() {
	cat <<EOF
NAME
    `basename $PROGNAME` - Copy tabsep from in to out, obeying ~/.geo-mystery

SYNOPSIS
    `basename $PROGNAME` [options]

DESCRIPTION
    Copy tabsep from in to out, obeying ~/.geo-mystery

OPTIONS
    -m		Only mystery
    -D lvl	Debug level
EOF

	exit 1
}

#
#       Report an error and exit
#
error() {
	echo "`basename $PROGNAME`: $1" >&2
	exit 1
}

debug() {
	if [ $DEBUG -ge $1 ]; then
	    echo "`basename $PROGNAME`: $2" >&2
	fi
}

#
#	tabsep2tabsep puzzle-file 
#
tabsep2tabsep() {
    if [ ! -e "$1" ]; then
	error "Don't have a -M '$1' file"
    fi

    awk -v GEOMYSTERY="$1" -v ONLYMYSTERY="$ONLYMYSTERY" '
    function latlon ( val ) {
	if (val ~ ".[.]..*[.].*")
	{
	    if (val ~ "[-wWsS]")
	    {
		val = substr(val, 2)
		neg = 1
	    }
	    else if (val ~ "[nNeE]")
	    {
		val = substr(val, 2)
		neg = 0
	    }
	    else
		neg = 0
	    dd = int(val)
	    sub("[^.]*[.]", "", val)
	    dd += (val+0.0) / 60.0
	    return neg ? -dd : dd
	}
	return val
    }
    function fabs ( x ) { return (x >= 0) ? x : -x }
    function deg2intdeg ( d ) {
	if (d >= 0)
	    return int( (2147483647) - (d * 8388608) + 0.5 )
	else
	    return int( (2147483647) - (fabs(d) * 8388608) + 1 + 0.5 )
    }
    function lat_dir(a) { return a < 0.0 ? "S" : "N" }
    function lon_dir(a) { return a < 0.0 ? "W" : "E" }
    BEGIN {
	while (getline <GEOMYSTERY > 0)
	{
	    if ($0 ~ "^#")
		continue
	    if ($0 ~ "^[ 	]*$")
		continue
	    if ($2 ~ "unk")
	    {
		lat[$1] = 48
		lon[$1] = -88
	    }
	    else
	    {
		lat[$1] = $2
		lon[$1] = $3
	    }
	}
	FS="	"
    }
    {
	if (lat[$2] != 0)
	{
	    deglat = latlon( lat[$2] )
	    deglon = latlon( lon[$2] )
	    # id shortname desc notes URL urltext type lat lon
	    for (i = 1; i <= 7; ++i)
		printf "%s\t", $i

	    # lat lon
	    printf "%.6f\t%.6f\t", deglat, deglon

	    # intlat intlon
	    printf "%d\t%d\t", deg2intdeg(deglat), deg2intdeg(deglon)

	    #  lat_decdir lon_decdir ...
	    printf "%.6f%s\t%.6f%s\t", fabs(deglat), lat_dir(deglat),
		fabs(deglon), lon_dir(deglon)

	    #  lat_dirdeg lon_dirdeg ...
	    printf "%s%.6f\t%s%.6f\t", lat_dir(deglat), fabs(deglat),
		lon_dir(deglon), fabs(deglon)

	    # lat_dir lon_dir ...
	    for (i = 16; i < NF; ++i)
		printf "%s\t", $i

	    # GEOCACHE_LAST_FOUND
	    printf "%s\n", $NF
	}
	else if (ONLYMYSTERY == 0)
	    print
    }
    '
}

#
#       Process the options
#
DEBUG=0
ONLYMYSTERY=0
while getopts "D:h?" opt
do
	case $opt in
	m)	ONLYMYSTERY=1;;
	D)	DEBUG="$OPTARG";;
	h|\?)	usage;;
	esac
done
shift `expr $OPTIND - 1`

#
#	Main Program
#
tabsep2tabsep $HOME/.geo-mystery
