#!/bin/sh

PROGNAME="$0"

usage() {
	cat <<EOF
NAME
	`basename $PROGNAME` - GPX file merge

SYNOPSIS
	`basename $PROGNAME` [options] file(s) ...

DESCRIPTION
	GPX file merge.  Output to stdout.

OPTIONS
	-D lvl	Debug level
EOF

	exit 1
}

#
#       Report an error and exit
#
error() {
	echo "`basename $PROGNAME`: $1" >&2
	exit 1
}

debug() {
	if [ $DEBUG -ge $1 ]; then
	    echo "`basename $PROGNAME`: $2" >&2
	fi
}

#
#       Process the options
#
DEBUG=0
while getopts "D:h?" opt
do
	case $opt in
	D)	DEBUG="$OPTARG";;
	h|\?)	usage;;
	esac
done
shift `expr $OPTIND - 1`

#
#	Main Program
#
if [ $# = 0 ]; then
	usage
fi

files=
for i in $*; do
    if [ -s "$i" ]; then
	files="$files -f $i"
    fi
done
if [ "" = "$files" ]; then
    exit
fi
gpsbabel -igpx -ogpx $files -F-
