#!/bin/sh

PROGNAME="$0"

usage() {
	cat <<EOF
NAME
    `basename $PROGNAME` - Convert .nono to teal format

SYNOPSIS
    `basename $PROGNAME` [options]

DESCRIPTION
    Convert .nono to teal format.

OPTIONS
    -D lvl	Debug level

EXAMPLE
    Convert GC7CJ4W-w.nono to a teal format:

	$ nono2teal < ~/proj/caches/GC7CJ4W-w.nono
	{"ver":[[2,2,1,1,3,3,1,2,2,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1],
	[2,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,5],
	[2,2,3,1,1,3,1,1,3,1,1],[4,3,3,3,2,3],[1,1,1,1,1,1,1,1,1,1],
	[1,2,1,1,3,3,2,2],[1,1,1,1,1,1,1,1,1,1,1],
	[2,3,2,2,2,2,3,3,1,1,4,2,3],
	[1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1],
	[2,3,2,2,1,1,2,1,1,4,1,2,2,2],
	[1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1],
	[2,1,2,2,2,2,1,3,1,1,4,2,1,1]],
	"hor":[[3,1,3,1],[1,3,1,3],[5],[6,6],[1,2,1,2,1],[1,6],[5],
	[11],[6,2,1,1],[5],[1,5],[11,1,1],[1,1,1,1],[10],[1,1,1],
	[10,3],[1,1,1,1],[8,1],[5,1,3],[6],[2,1,2],[5],[11],
	[1,1,2,1],[2,3,1],[5,5],[1,1,1,1], [0],[5,5],[1,2],[1,2],
	[5],[4],[2,5],[2,1,1],[2,1,1,1],[4,1,3],[0],[5],
	[1,1,1],[0],[5],[1],[2,2]]}

SEE ALSO
    geo-nonogram, nono2cross+a, nono2jsolver

    http://a.teall.info/nonogram/

    http://webpbn.com/export.cgi
EOF

	exit 1
}

#
#       Report an error and exit
#
error() {
	echo "`basename $PROGNAME`: $1" >&2
	exit 1
}

debug() {
	if [ $DEBUG -ge $1 ]; then
	    echo "`basename $PROGNAME`: $2" >&2
	fi
}

#
#       Process the options
#
DEBUG=0
#unset OPTIND
while getopts "D:h?" opt
do
	case $opt in
	D)	DEBUG="$OPTARG";;
	h|\?)	usage;;
	esac
done
shift `expr $OPTIND - 1`

#
#	Main Program
#
awk '
BEGIN {
    printf "{"
}
/rows/ {
    inrows=1
    first = 1
    printf "\"ver\":["
    next
}
/columns/ {
    inrows=0
    incols=1
    first = 1
    printf "],\"hor\":["
    next
}
inrows == 1 || incols == 1 {
    if ($0 == "") next
    text = $0
    gsub(/ /, ",", text)
    printf "%s[%s]", first == 0 ? "," : "", text
    first = 0
}
END {
    printf "]}\n"
}
'
